name: deployToGhPages
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages_attempt'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build site
        run: yarn run build

      - name: build site
        run: yarn run deploy
